name: Patch Image via URL

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Recovery Image URL'
        default: 'https://catbox.moe/ (recovery.img.lz4)'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Gain file access
      uses: actions/checkout@v4.1.1
    
    - name: Fetch necessary packages
      run: |
         sudo apt install git wget lz4 tar openssl python3 -y
         
    - name: Download recovery image from URL
      run: |
         wget -O recovery.img.lz4 ${{github.event.inputs.image_url}} --no-check-certificate

    - name: Start patching script
      run: |
         chmod a+x magiskboot
         chmod a+x patcher-minimal
         chmod a+x avbtool
         ./patcher-minimal

    - name: Upload patched image files
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/fastboot-patcher/fastboot-patcher/output/*.md5
        name: Patched Recovery Image Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true
        
    - name: Upload keys for patched image
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/fastboot-patcher/fastboot-patcher/keys/*.*
        name: Patched Image Key Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true
